name: asesorias_fic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Paquetes de utilidad e interfaz de usuario
  file_picker: ^11.0.2
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  http: ^1.6.0
  provider: ^6.1.5+1
  
 
  flutter_secure_storage: ^10.3.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Configuración de Fuentes Oficiales
  fonts:
    - family: Iner
      fonts:
        - asset: fonts/Inder-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-SemiBold.ttf

  # Mapeo de Assets y Formatos de Excel de la FIC
  assets:
    - assets/images/fic_logo.png
    - assets/images/foto_icon.png
    - assets/images/logo_blanco.png
    - assets/images/cargarImagen.png
    - assets/data/
    - assets/images/
    - assets/images/dependencias/
    - assets/formatos/FormatoAlumnos.xlsx
    - assets/formatos/FormatoAsesoresPar.xlsx
    - assets/formatos/FormatoAsesoresDiciplinares.xlsx